# Generated by Django 4.1.7 on 2023-09-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_delete_truncatetable_remove_values_membership_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='values',
            name='transactionid',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
