# Generated by Django 4.1.7 on 2023-09-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_values_transactionid'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUserTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=100)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
    ]
