# Generated by Django 4.1.7 on 2023-09-05 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_adminusertable'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdminUserTable',
            new_name='Admin',
        ),
    ]
