# Generated by Django 4.0.6 on 2023-09-07 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_adminusertable_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='values',
            name='appliedfor',
            field=models.CharField(default='', max_length=100),
        ),
    ]
