# Generated by Django 4.1.7 on 2023-09-05 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_annualreportindexpage_annualreportpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferencepage',
            name='type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
